### ISSUE TITLE
uniapp开发，按照文档正常引入，H5正常，微信小程序报错

### ISSUE THREAD

**Issue by mefan** [Mihawk-zhao/minapp-fetch#1]
default  方式引入
```
TypeError: Cannot read property 'toStringTag' of undefined
    at e.exports (spread.js:25)
    at Object.<anonymous> (spread.js:25)
    at n (spread.js:25)
    at Object.<anonymous> (spread.js:25)
    at n (spread.js:25)
    at Object.<anonymous> (spread.js:25)
    at n (spread.js:25)
    at Object.<anonymous> (spread.js:25)
    at n (spread.js:25)
    at Object.<anonymous> (spread.js:25)
```

**Comment by Mihawk-zhao** [comment]
那我看看，因为没有用uniapp开发，就没测试到

**Comment by Mihawk-zhao** [comment]
那我看看，因为没有用过uniapp

**Comment by Mihawk-zhao** [comment]
这个 ‘toStringTag’ 好像是官方的包'minapp-sdk'的问题。。你可以以js-sdk本地版本引入。然后
用：const minapp = require('minapp-fetch').init('weapp')引入就可以了。

<img width="418" alt="WeChat0c03ffad3bb37eb5290b60bf03c5a559" src="https://user-images.githubusercontent.com/19793378/78258158-682d5180-752d-11ea-82c7-04e349e05bce.png">
<img width="518" alt="WeChatdb656ae756c2ba0aa627ec84ceffccbf" src="https://user-images.githubusercontent.com/19793378/78258183-6fecf600-752d-11ea-96d9-9d8ff1a52bca.png">

**Comment by Mihawk-zhao** [comment]
如果你想多端同时开发，，可以定义可变参数，，
```js
let args = ['weapp']  // ['default', 'adi23fv234jk2j423']

//其他页面
const minapp = require('minapp-fetch').init(...args)
```

**Comment by mefan** [comment]
感谢回答，后来我在 var BaaS_d = require('minapp-sdk'); 加了 /lib/index 就可以运行了，但是我还是没想明白原因。。。
![image](https://user-images.githubusercontent.com/4438786/78277841-ba7b6c00-7547-11ea-952a-6f611d11f497.png)

**Comment by Mihawk-zhao** [comment]
我也不大清楚了，，可能是sdk没有识别环境
