### ISSUE TITLE
在uniapp中使用webapi方式，android真机报错

### ISSUE THREAD

**Issue by haskx** [Mihawk-zhao/minapp-fetch#2]
报错信息：
TypeError: adapter is not a function. (In 'adapter(config)', 'adapter' is undefined)
在uniapp中，使用webapi方式
`// #ifdef APP-PLUS
			minapp = require('minapp-fetch').init('webapi', {
				clientID: 'xxx', //必填
				  host: 'https://xxx.myminapp.com',  //为自定义域名(如: https://api.wefishbone.com)
			});
			
			// #endif`
使用上述代码，开启调试的情况下调用find是ok的，但是不开调试真机就报错了。

**Comment by Mihawk-zhao** [comment]
会不会是你哪里的代码有写错了呀。。这个包里面，是没有 adapter 这个参数或函数的

**Comment by Mihawk-zhao** [comment]
这个好像是 axios 请求的问题

**Comment by Mihawk-zhao** [comment]
https://ext.dcloud.net.cn/plugin?id=558#detail你试试这个呢

**Comment by Mihawk-zhao** [comment]
你试试这个呢
https://ext.dcloud.net.cn/plugin?id=558#detail
